### ISSUE TITLE
[Android] cmake 빌드 과정을 따르는 Android 버젼의 Player 구현

### ISSUE THREAD

**Issue by juhl** [PolygonTek/BlueshiftEngine#1]
통합된 소스 관리를 위해서 다른 플랫폼 (Windows/macOS/iOS) 과 마찬가지로 Android 버젼에서도 cmake 를 사용해야 합니다.
 
cmake 빌드 과정에 통합된 BlueshiftPlayer 의 Android 버젼이 구현되면, 기존 vs2015 프로젝트인 Engine/Project/Android 는 제거될 예정입니다.

**Comment by sj6219** [comment]
아직 CMake 에서 Tegra-Android 를 완벽하게 지원하지 않아서 불가능합니다.

Android 버젼의 static library 는 만들수 있지만, Native Android App 프로젝트는 만들 수가 없습니다.
