### ISSUE TITLE
[Editor] Keep Crashing on start-up

### ISSUE THREAD

**Issue by ghost** [PolygonTek/BlueshiftEngine#23]
i do not know if it was crash or just stuck. but everytimes i start the editor the "windows problem reporting" always appeared in the task manager, and the editor windows is never appeared. what possibly i have missed?

**Comment by juhl** [comment]
Please let me know the execution environment first. Graphics card, OS version, etc.

And did you run the 0.4 version? Or did you compile the engine yourself?

If you run the editor for the first time, a dialog box will pop up to find the project directory. If it crashes before the dialog, run regedit.exe and delete `HKEY_CURRENT_USER / Software / PolygonTek`. And re-run it.

**Comment by ghost** [comment]
it was : 
- Windows 10 home 64bit
- the graphic card : AMD Radeon HD 7400G
- the processor : AMD A4-4335 APU

i already set the project directory, exactly it crash after that, i have tried to re-run the editor but it still the same, i used the latest release of the editor and not yet compile the engine myself

**Comment by juhl** [comment]
Was the project directory you were trying to open `BasicGame` ? 

If so, can you see the `BasicGame/Log/log.txt` ?

**Comment by ghost** [comment]
the editor is did not want to running, how could i create or even open any project?

**Comment by juhl** [comment]
Did you download example project ? [Example Projects](https://github.com/PolygonTek/BlueshiftExamples/archive/master.zip)

Not supported creating new project in editor yet. (will be fixed)

If the editor does not appear on the screen, delete the registry key again.

**Comment by ghost** [comment]
not yet, hold on sec

**Comment by ghost** [comment]
its works now, i'm sorry i did not know if the sample is required to run the editor, thanks for the assist

**Comment by ghost** [comment]
anyway, where is the lua scripting reference i can read?

**Comment by juhl** [comment]
I'm planning to make scripting API documentation. You can see the issue #19.
Until then you can reference the source code (cpp) to use.
https://github.com/PolygonTek/BlueshiftEngine/tree/master/Source/BlueshiftEngine/Private/Script
Or see the sample script. 

I know that it is inconvenient to use. But please understand that it is an alpha stage engine.
It will be improved later.

**Comment by ghost** [comment]
it's okay, i'm okay with learning from example, i'm surely understand, i keep support your development, i looking forward for future features implementation

**Comment by juhl** [comment]
Thank you for your support. 😃
