### ISSUE TITLE
could you open editor sources?

### ISSUE THREAD

**Issue by xcultivate** [PolygonTek/BlueshiftEngine#24]
when i use cmake 
CMake Warning at Source/ThirdParty/ToolWindowManager/CMakeLists.txt:29 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at Source/ThirdParty/ToolWindowManager/CMakeLists.txt:31 (qt5_wrap_cpp):
  Unknown CMake command "qt5_wrap_cpp".

**Comment by juhl** [comment]
Building editor from source code are not available for now.

To build the engine from source code, you can follow the instructions below.

https://github.com/PolygonTek/BlueshiftEngine/wiki/How-to-Build-Engine-Runtime-Libraries

We don't have any plan to release full source code including editor yet.
