### ISSUE TITLE
Error In Open GuidMap

### ISSUE THREAD

**Issue by mikrokode** [PolygonTek/BlueshiftEngine#27]
Friend,

I got error when running these code, May I know Why?Couldn't open guidmap

if (!BE1::resourceGuidMapper.Read("Data\\guidmap")) {
        BE_FATALERROR("Couldn't open guidmap !");
    }

**Comment by juhl** [comment]
It means that you ran BlueshiftPlayer.exe in the wrong location.

Running BlueshiftPlayer.exe from the source code is not currently recommended. I will add the document later.

Thanks.
